version: '3.8'

services:
  morphotv-proxy:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.morphotv-proxy.rule=Host(`proxy.morphotv.local`)"
      - "traefik.http.services.morphotv-proxy.loadbalancer.server.port=8080"
